#ifndef SRC_COMMON_H_
#define SRC_COMMON_H_

enum RETURN_CODES {
    OK = 0, GENERAL_ERROR = 1, PARSE_ERROR = 3, VALIDATION_ERROR = 4, SSL_INIT_ERROR = 5, DOWNLOAD_ERROR = 6, SELECT_ERROR = 7
};

#endif /* SRC_COMMON_H_ */
